<?php
/**
 * MemoryApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * OpenAPI spec version: 0.0.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MemoryApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MemoryApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deletePointInMemory
     *
     * Delete Point In Memory.
     *
     */
    public function testDeletePointInMemory()
    {
    }

    /**
     * Test case for getCollections
     *
     * Get Collections.
     *
     */
    public function testGetCollections()
    {
    }

    /**
     * Test case for getConversationHistory
     *
     * Get Conversation History.
     *
     */
    public function testGetConversationHistory()
    {
    }

    /**
     * Test case for recallMemoriesFromText
     *
     * Recall Memories From Text.
     *
     */
    public function testRecallMemoriesFromText()
    {
    }

    /**
     * Test case for wipeCollections
     *
     * Wipe Collections.
     *
     */
    public function testWipeCollections()
    {
    }

    /**
     * Test case for wipeConversationHistory
     *
     * Wipe Conversation History.
     *
     */
    public function testWipeConversationHistory()
    {
    }

    /**
     * Test case for wipeMemoryPoints
     *
     * Wipe Memory Points By Metadata.
     *
     */
    public function testWipeMemoryPoints()
    {
    }

    /**
     * Test case for wipeSingleCollection
     *
     * Wipe Single Collection.
     *
     */
    public function testWipeSingleCollection()
    {
    }
}
