<?php
/**
 * PluginsApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * 😸 Cheshire-Cat API
 *
 * Customizable AI architecture
 *
 * OpenAPI spec version: 0.0.5
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PluginsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PluginsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deletePlugin
     *
     * Delete Plugin.
     *
     */
    public function testDeletePlugin()
    {
    }

    /**
     * Test case for getPluginDetails
     *
     * Get Plugin Details.
     *
     */
    public function testGetPluginDetails()
    {
    }

    /**
     * Test case for getPluginSettings
     *
     * Get Plugin Settings.
     *
     */
    public function testGetPluginSettings()
    {
    }

    /**
     * Test case for getPluginsSettings
     *
     * Get Plugins Settings.
     *
     */
    public function testGetPluginsSettings()
    {
    }

    /**
     * Test case for installPlugin
     *
     * Install Plugin.
     *
     */
    public function testInstallPluginForm()
    {
    }

    /**
     * Test case for installPluginFromRegistry
     *
     * Install Plugin From Registry.
     *
     */
    public function testInstallPluginFromRegistry()
    {
    }

    /**
     * Test case for listAvailablePlugins
     *
     * List Available Plugins.
     *
     */
    public function testListAvailablePlugins()
    {
    }

    /**
     * Test case for togglePlugin
     *
     * Toggle Plugin.
     *
     */
    public function testTogglePlugin()
    {
    }

    /**
     * Test case for upsertPluginSettings
     *
     * Upsert Plugin Settings.
     *
     */
    public function testUpsertPluginSettings()
    {
    }
}
